{
 "title": "Power",
 "tags": [ "showcase" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Frequency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    {
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(\"value\") AS \"Power L1\" FROM \"mqtt_consumer\" WHERE (\"topic\" = 'sdm630/Instrument23/WLocPhsA') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "sdm630/Instrument23/Freq" }
     ]
    }
   ]
  },
  {
   "title": "Current Power",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT \"value\" FROM \"mqtt_consumer\" WHERE (\"topic\" = 'sdm630/Instrument23/WLocPhsA') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "sdm630/Instrument23/WLocPhsA" },
      { "condition": "OR", "key": "topic", "operator": "=", "value": "sdm630/Instrument23/WLocPhsB" },
      { "condition": "OR", "key": "topic", "operator": "=", "value": "sdm630/Instrument23/WLocPhsC" }
     ]
    }
   ]
  },
  {
   "title": "Import",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(\"value\") AS \"Power L1\" FROM \"mqtt_consumer\" WHERE (\"topic\" = 'sdm630/Instrument23/WLocPhsA') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "-1804" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "sdm630/Instrument23/TotkWhImport"
      }
     ]
    }
   ]
  },
  {
   "title": "Estimated Cost",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "mqtt_consumer",
     "query": "SELECT (\"value\" -1804)*0.25 FROM \"mqtt_consumer\" WHERE (\"topic\" = 'sdm630/Instrument23/TotkWhImport') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "-1804*0.25" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "sdm630/Instrument23/TotkWhImport"
      }
     ]
    }
   ]
  },
  {
   "title": "Current L1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    {
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(\"value\") AS \"Power L1\" FROM \"mqtt_consumer\" WHERE (\"topic\" = 'sdm630/Instrument23/WLocPhsA') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "sdm630/Instrument23/AmpLocPhsA" }
     ]
    }
   ]
  },
  {
   "title": "Current L2",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    {
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(\"value\") AS \"Power L1\" FROM \"mqtt_consumer\" WHERE (\"topic\" = 'sdm630/Instrument23/WLocPhsA') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "sdm630/Instrument23/AmpLocPhsB" }
     ]
    }
   ]
  },
  {
   "title": "Current L3",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    {
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(\"value\") AS \"Power L1\" FROM \"mqtt_consumer\" WHERE (\"topic\" = 'sdm630/Instrument23/WLocPhsA') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "sdm630/Instrument23/AmpLocPhsC" }
     ]
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Voltage L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "sdm630/Instrument23/VolLocPhsA" }
     ]
    },
    {
     "alias": "Voltage L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "sdm630/Instrument23/VolLocPhsB" }
     ]
    },
    {
     "alias": "Voltage L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "sdm630/Instrument23/VolLocPhsC" }
     ]
    }
   ]
  },
  {
   "title": "Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "Current L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "sdm630/Instrument23/AmpLocPhsA" }
     ]
    },
    {
     "alias": "Current L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "sdm630/Instrument23/AmpLocPhsB" }
     ]
    },
    {
     "alias": "Current L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "sdm630/Instrument23/AmpLocPhsC" }
     ]
    }
   ]
  }
 ]
}