{
 "title": "WLAN",
 "tags": [ "showcase" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total Connected Clients",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "global_stats",
     "select": [
      [
       { "params": [ "activeUser" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Connected APs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "global_stats",
     "select": [
      [
       { "params": [ "connectedAp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "ap_general",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Uptime" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clients per AP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ap_general",
     "query": "SELECT non_negative_derivative(mean(2g_rxBytes),1s) FROM \"ap_general\" WHERE $timeFilter GROUP BY time(1m), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "clientNum" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ssid_stats",
     "select": [
      [
       { "params": [ "totalDownload" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ssid", "operator": "=", "value": "ICMP9" }
     ]
    }
   ]
  },
  {
   "title": "Total Up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ssid_stats",
     "select": [
      [
       { "params": [ "totalUpload" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ssid", "operator": "=", "value": "ICMP9" }
     ]
    }
   ]
  },
  {
   "title": "Data Rates per AP [2.4GHz]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ap_general",
     "query": "SELECT non_negative_derivative(mean(2g_rxBytes),1s) FROM \"ap_general\" WHERE $timeFilter GROUP BY time(1m), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "2g_rxBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Up" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ap_general",
     "query": "SELECT non_negative_derivative(mean(2g_rxBytes),1s) FROM \"ap_general\" WHERE $timeFilter GROUP BY time(1m), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "2g_txBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Down" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Rates per AP [5GHz]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "ap_general",
     "query": "SELECT non_negative_derivative(mean(2g_rxBytes),1s) FROM \"ap_general\" WHERE $timeFilter GROUP BY time(1m), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "5g_rxBytes" ], "type": "field" },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Up" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "ap_general",
     "query": "SELECT non_negative_derivative(mean(2g_rxBytes),1s) FROM \"ap_general\" WHERE $timeFilter GROUP BY time(1m), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "5g_txBytes" ], "type": "field" },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "Down" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}